# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  app:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    # environment:
    #   - DB_HOST=mariadb
    #   - DB_PORT=3306
    #   - DB_USERNAME=bn_app
    #   - DB_DATABASE=bitnami_app
    volumes:
      - './graduation-project:/app'
    depends_on:
      - mariadb
